

services:
  db_comercial_db:
    image: postgres:16.1
    container_name: db_comercial_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bi_comercial_db
      POSTGRES_USER: bi_user
      POSTGRES_PASSWORD: bi_pass
    ports:
      - "5782:5432"
    volumes:
      - db_comercial_db_data:/var/lib/postgresql/data
      - ../../db/init/cria_banco.sql:/docker-entrypoint-initdb.d/01-cria_banco.sql:ro

volumes:
  db_comercial_db_data:
